name:                gast-werk-gui
version:             0.1.0.0
github:              "neuroliptica/gast-werk-gui"
license:             MIT
author:              "Neuroliptica"
maintainer:          "@neuroliptica"
copyright:           "2023 Neuroliptica"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gast-werk-gui#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk
- haskell-gi-base
- logging
- text
- directory
- http-conduit
- aeson
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-do-bind
- -Wno-unused-imports
- -Wno-missing-home-modules

library:
  source-dirs: src

executables:
  gast-werk-gui-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gast-werk-gui

